version: "3"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/raissa/repo/wishlist_mongo/database:/data/db
    ports:
      - 27017:27017
    networks:
      - mongo-network
networks:
  mongo-network:
    driver: bridge
